### ISSUE TITLE
Build script to generate Mocks fails when path has spaces

### ISSUE THREAD

**Issue by brianoqr** [Brightify/Cuckoo#160]
When running this script to generate the mocks it will fail if you have a directory name with spaces in it.  Specifically if a parent dir of your ProjectDIR has a space.

So I moved the script to run it outside of XCode with relative paths, then it seems to generate the files fine, however i still get and error on Line 21: of the run script.  Will lookup the exact error and add it asap. 

OUTPUT_FILE="$PROJECT_DIR/Tests/GeneratedMocks.swift"
echo "Generated Mocks File = $OUTPUT_FILE"

INPUT_DIR="$PROJECT_DIR"
echo "Mocks Input Directory = $INPUT_DIR"

${PODS_ROOT}/Cuckoo/run generate --testable "$PROJECT_NAME" \
--output "${OUTPUT_FILE}" \
"$INPUT_DIR/FileName1.swift" \
"$INPUT_DIR/FileName2.swift" \
"$INPUT_DIR/FileName3.swift"

**Comment by TadeasKriz** [comment]
Thank you for this report. Please try to change the `${PODS_ROOT}/Cuckoo/run generate` to `"${PODS_ROOT}/Cuckoo/run" generate`. It should resolve this problem. I'll update the run script.

**Comment by brianoqr** [comment]
Thanks, i should have seen that, PS: in the run script there is a linke regarding the $SCRIPT_INPUT_FILE_COUNT (the line 21 thing),  i beleive the value of  $SCRIPT_INPUT_FILE_COUNT is nothing so it gives and error, but the script continues, no worries

**Comment by joshuatbrown** [comment]
I believe this is still an issue when input file paths contain spaces. For example, one of my paths looks like this:

"$INPUT_DIR/Add\ Widget/AddWidgetViewController.swift"

If I `cat` the full path in Terminal, it prints the contents of the file, so it seems like my path is correct. Cuckoo just doesn't like it. It says:

> Could not read contents of `<full path goes here>/Add\ Widget/AddWidgetViewController.swift`

**Comment by MatyasKriz** [comment]
Yeah, you're using quotes so that you can omit the backslashes before spaces.

**Comment by joshuatbrown** [comment]
You're absolutely right — thanks!

**Comment by MatyasKriz** [comment]
Happy to help. 🙂
