### ISSUE TITLE
Builds failing on Bitrise with stack Xcode 13.3.x (beta)

### ISSUE THREAD

**Issue by brandtdaniels** [Brightify/Cuckoo#417]
Bitrise stack "Xcode 13.3.x (beta) on macOS 12.2 (Monterey)" is failing builds with the following error message

```
Last lines of the build log:
Script path: /Users/vagrant/git/CRM
xargs: /Users/vagrant/git/CRM/cuckoo_generator: terminated with signal 4; aborting
Command PhaseScriptExecution failed with a nonzero exit code

Test session results, code coverage, and logs:
	/var/folders/62/0p2cg52j6r16xjxfqch4vgt40000gn/T/XCUITestOutput573379856/Test.xcresult

Testing failed:
	Command PhaseScriptExecution failed with a nonzero exit code
	Testing cancelled because the build failed.

** TEST FAILED **

The following build commands failed:
	PhaseScriptExecution Cuckoo\ Run\ Script /Users/vagrant/Library/Developer/Xcode/DerivedData/CRM-gfmkxxwjwsejasaegkkqxuwbswfa/Build/Intermediates.noindex/CRM.build/Debug-iphonesimulator/CRMTests.build/Script-3312E990D1E37BD0916B2578.sh (in target 'CRMTests' from project 'CRM')
(1 failure)
```

Recently included the following conditionals in the Cuckoo Run Script which seems to have no improvement

```
if [ $ACTION == "indexbuild" ]; then
  echo "Not running Cuckoo generator during indexing."
  exit 0 
fi

# Skip for preview builds
if [ "${ENABLE_PREVIEWS}" = "YES" ]; then
  echo "Not running Cuckoo generator during preview builds."
  exit 0
fi
```

**Comment by brandtdaniels** [comment]
@MatyasKriz Have you seen any issues with the latest Xcode beta?

**Comment by MatyasKriz** [comment]
Hey, @brandtdaniels. I haven't tried compiling nor running Cuckoo on the beta builds of Xcode. Not sure what the issue could be.

**Comment by MatyasKriz** [comment]
Is there more info somewhere in the logs? My internet connection isn't stellar to download the Xcode beta just to find an issue.

**Comment by brandtdaniels** [comment]
I didn't really see anything more in the logs

**Comment by MatyasKriz** [comment]
Is it possible to switch to an earlier Xcode on Bitrise, or is this just a heads up that Cuckoo fails to run in Xcode 13.3 beta?

**Comment by brandtdaniels** [comment]
We typically prepare for upcoming versions of Xcode/iOS as soon as they become available. We try to catch these issues proactively.

**Comment by KarimAlweheshy** [comment]
For me it is failing on lastest xcode `xargs: /{fill_in_dir}/Pods/Cuckoo/cuckoo_generator: terminated with signal 5; aborting`

**Comment by jandrewmoore** [comment]
My project is failing after updating Xcode, as well, but with signal 4.
```
xargs: [redacted]/Pods/Cuckoo/cuckoo_generator: terminated with signal 4; aborting
Command PhaseScriptExecution failed with a nonzero exit code
```
Doesn't seem like adding `--debug` is adding any additional information in this case.

**Comment by antoniocasero** [comment]
Same problem here, usually, I would try my best to fix it, but it crashes without reason.
I observed this issue only happens for some specific files.

**Comment by antoniocasero** [comment]
Ok, after exploring why only some files were making the script crash. I found out that if the protocol defines a function without a label, it crashes.

```
func foo(_ bar: Bar) // It crashes
func foo(bar: Bar) // All good
```

**Comment by JavaAdam** [comment]
> My project is failing after updating Xcode, as well, but with signal 4.
> 
> ```
> xargs: [redacted]/Pods/Cuckoo/cuckoo_generator: terminated with signal 4; aborting
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> Doesn't seem like adding `--debug` is adding any additional information in this case.

It's the same for me.

**Comment by dongdonggaui** [comment]
> Ok, after exploring why only some files were making the script crash. I found out that if the protocol defines a function without a label, it crashes.
> 
> ```
> func foo(_ bar: Bar) // It crashes
> func foo(bar: Bar) // All good
> ```

It seems that SourceKit has been updated. When parsing parameters without a label such as `func foo(_ bar: Bar)`, the parameter `key.nameoffset` and `key.namelength` 2 values are lost.

**Comment by MatyasKriz** [comment]
Hey everyone! Thanks a lot for the leads, especially @antoniocasero and @dongdonggaui for finding the issue. 🙂 I've verified that the problem is indeed because of the missing properties, though the name range isn't used, so I've just made it optional for now.

I've merged and released the fix, please try it out and let me know if it helped. 🙂

**Comment by brandtdaniels** [comment]
> I've merged and released the fix, please try it out and let me know if it helped. 🙂

Does it take time to propagate the release? The update isn't being picked up when trying to update the package on my end.

**Comment by MatyasKriz** [comment]
> Does it take time to propagate the release?

Which package manager?

**Comment by MatyasKriz** [comment]
I see, that's my bad. The change here actually isn't in Cuckoo itself, but the generator, but the binary hasn't been uploaded for some reason. I've fixed that, so now the newest one should get downloaded. 🙂

**Comment by brandtdaniels** [comment]
@MatyasKriz I'm getting this error message when trying to resolve packages:

```
Dependencies could not be resolved because root depends on 'Cuckoo' 1.7.0..<2.0.0.
'Cuckoo' >= 1.7.0 cannot be used because package 'cuckoo' is required using a stable-version but 'cuckoo' depends on an unstable-version package 'ocmock' and no versions of 'Cuckoo' match the requirement 1.7.1..<2.0.0.
```

**Comment by MatyasKriz** [comment]
@brandtdaniels hm, I see, that must be the addition of OCMock, I'll see what I can do. In the meantime, as these changes are in the generator binary only, you can fallback to `1.6.0` for now.

**Comment by brandtdaniels** [comment]
> @brandtdaniels hm, that must be the addition of OCMock, I'll see what I can do. In the meantime, as these changes are in the generator binary only, you can fallback to `1.6.0` for now.

Can you clarify how 1.6.0 on SPM will pick up the new generator? I know there were some steps I took to manually copy some scripts/binaries into the project to get Cuckoo to work with SPM.

**Comment by MatyasKriz** [comment]
> Can you clarify how 1.6.0 on SPM will pick up the new generator?

The `run` script is responsible for downloading and running the generator. SwiftPM itself is way too limited for that.

**Comment by MatyasKriz** [comment]
@ajpallares sorry to ping you in this issue, but do you happen to know how to work around the OCMock unstability?

**Comment by sskjames** [comment]
Hi @MatyasKriz, using cocoapods here, got the Cuckoo 1.7.0 release. It's working for me. Thank you very much for the fix.

**Comment by ajpallares** [comment]
@MatyasKriz I'm afraid that a simple workaround is not possible. It looks like referencing a dependency using the commit hash or branch name) is considered an "unstable reference" by SPM. And a stable reference, i.e. a tag, can only depend on unstable references... (a better explanation [here](https://forums.swift.org/t/dependencies-could-not-be-resolved-because-package-yeelampa-is-required-using-a-stable-version-but-yeelampa-depends-on-an-unstable-version-package-requester-and-root-depends-on-yeelampa-0-1-0/53840/2))
This was my mistake, I did not realize of this limitation of the SPM.

This is, in fact, pointed out in the very [OCMock repo](https://github.com/erikdoe/ocmock/issues/500#issuecomment-955731638), but which I did not see beforehand :( 

There might be a [possible workaround](https://forums.swift.org/t/confused-by-unsafe-flags-being-disallowed-in-dependencies/27359/27) for this, which involves having a local Swift Package which wraps the unstable package. I need to investigate this in depth. We might take advantage of the fact that we actually need to have the Swift wrapper Cuckoo+OCMock.

Sorry for the inconvenience and I hope I can solve this soon using that workaround.

**Comment by MatyasKriz** [comment]
@ajpallares thanks for the thorough analysis. 🙂 Don't worry about it, this kind of stuff happens. I'm glad you're here to help us push through. I'll release 1.7.1 without the SPM changes for now, so there's no pressure at all.

**Comment by MatyasKriz** [comment]
@brandtdaniels Depending on how you call the `run` script, you can download a specific version of the generator or the latest one if no version is specified. However, this happens only if there isn't a generator binary already present. To override, pass the `--clean‘ flag as well.

**Comment by brandtdaniels** [comment]
To work with SPM, I had to download the latest `cuckoo_generator` Add execute permissions `chmod +x cuckoo_generator` and commit to my repository. I was then able to build and run specs on Xcode 13.3.x

**Comment by MatyasKriz** [comment]
@brandtdaniels I'd highly recommend against commiting binaries into the git repo. Every time you update a binary in git, it  essentially doubles in size. I'd also suggest you delete the commits that added the binary in the first place.

The problem you're facing is that there's no way for us to update your `run` script at the moment, as it has been fixed a while back. Simply download the latest `run` script from master and run it with arguments `--download --clean`. Let me know if that works for you.

**Comment by jgavris** [comment]
If you're using Git LFS (large file storage), you can check in the binaries (cuckoo generator etc) into your repo and mostly have constant size over time, which is not terrible. Aka if you upgrade cuckoo a few times, the overall repo / checkout size won't change. 

Git LFS only requires downloading the versions of the files (tracked by LFS) that are reachable from the commit you are checking out, not every delta in between like normal git tracked files. We (and possibly a lot of other Cocoapods users) 'vendor' the entire `Pods` directory into git repo (checked in) and added this hook to our `Podfile` to automatically track any files over 300k (change to suite your taste) after running `pod install`.

```
post_install do |installer_representation|
  # Update git-lfs tracked files.
  Dir.chdir("Pods") do
    system "rm -f .gitattributes | find . -size +300k | xargs git lfs track"
    system "sort -n .gitattributes > /tmp/.gitattributes && mv /tmp/.gitattributes .gitattributes"
  end
end
```

Automatic tracking of large files in Git LFS is a highly requested feature (see https://github.com/git-lfs/git-lfs/issues/282), but one fairly easily worked around with a little bit of scripting.

**Comment by MatyasKriz** [comment]
@jgavris I don't know your setup and I assumed that the binary was not in LFS. Of course, if you want to keep the binary in the repo, it's your call. 🙂

**Comment by brandtdaniels** [comment]
> Simply download the latest `run` script from master and run it with arguments `--download --clean`. Let me know if that works for you.

It looks like the run script on master hasn't been updated in 2 years

**Comment by MatyasKriz** [comment]
> > Simply download the latest `run` script from master and run it with arguments `--download --clean`. Let me know if that works for you.
> 
> 
> 
> It looks like the run script on master hasn't been updated in 2 years

I see, time flies. 😅 Though the current version seems to work without problems.

**Comment by brandtdaniels** [comment]
> @brandtdaniels I'd highly recommend against commiting binaries into the git repo. Every time you update a binary in git, it essentially doubles in size. I'd also suggest you delete the commits that added the binary in the first place.
> 
> The problem you're facing is that there's no way for us to update your `run` script at the moment, as it has been fixed a while back. Simply download the latest `run` script from master and run it with arguments `--download --clean`. Let me know if that works for you.

After removing the binary from the repo, and adding `--clean --download` to the script, I am facing the same problem I originally had with Xcode 13.3.x:

```
 The following build commands failed:
	PhaseScriptExecution Cuckoo\ Run\ Script /Users/vagrant/Library/Developer/Xcode/DerivedData/CRM-gfmkxxwjwsejasaegkkqxuwbswfa/Build/Intermediates.noindex/CRM.build/Debug-iphonesimulator/CRMTests.build/Script-3312E990D1E37BD0916B2578.sh (in target 'CRMTests' from project 'CRM')
(1 failure)
````

**Comment by MatyasKriz** [comment]
Let's keep this issue closed and not ping all the other participants with debugging. The original issue has been fixed and now we just need to find out how to get your build script to correctly download the latest binary. Please open a new issue with some more information – if you run the `run` script by itself with the parameters, does it work? You mentioned something about a custom script, can that cause interference somehow?

**Comment by ppamorim** [comment]
@MatyasKriz This is not fixed, it's returning signal 9 on `cuckoo` runner.
